from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate
from langchain_core.documents import Document
from typing import List
from pydantic import BaseModel, Field

def split_text(text, chunk_size=1000, chunk_overlap=200):
    """
    Splits text into chunks using RecursiveCharacterTextSplitter with custom logic.
    If text length is less than 1.5 * chunk_size, returns a single chunk.
    Otherwise, splits with specified overlap.
    Returns a list of Document objects.
    """
    if not text:
        return []
        
    # Custom logic: if text is short enough, keep it whole
    if len(text) < (chunk_size * 1.5):
        return [Document(page_content=text)]
        
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        separators=["\n\n", "\n", " ", ""]
    )
    return text_splitter.create_documents([text])


class Section(BaseModel):
    """A logical section of the document."""
    summary: str = Field(
        description=(
            "Write 3–5 sentences. The summary must fully represent the chunk's content "
            "for vector search — it is the ONLY text that will be embedded and indexed. "
            "You MUST include:\n"
            "1. The situation or problem this chunk addresses\n"
            "2. The core behavior or conclusion\n"
            "Never omit keywords. Every proper noun and technical identifier in the "
            "content must also appear in the summary."
        )
    )
    context: str = Field(
        description=(
            "Optional. A 1-sentence description of the previous chunk's content, "
            "to be placed before this chunk as context. "
            "Leave empty for the first chunk."
        ),
        default=""
    )
    content: str = Field(
        description="Preserve the original text exactly as-is. Do not modify it in any way."
    )

class PageSections(BaseModel):
    """The structured output containing all sections of the page."""
    sections: List[Section]

def split_text_with_llm(text, model_name="gpt-5-mini"):
    """
    Splits the full text into logical sections using an LLM.
    Returns a list of Document objects, where each document is a section.
    Metadata includes the summary generated by the LLM.
    """
    if not text:
        return []
        
    llm = ChatOpenAI(model=model_name, temperature=0)
    structured_llm = llm.with_structured_output(PageSections)
    
    prompt = (
        "You are a technical documentation processor specializing in RAG pipeline preparation.\n\n"
        "## Goal\n"
        "Split the documentation into chunks where each chunk can independently answer "
        "a specific user question without requiring context from other chunks.\n\n"
        "## Chunking Rules\n"
        "1. Each chunk should represent only ONE distinct concept, behavior, or use case.\n"
        "2. Aim for 100 to 300 words per chunk. "
        "If a chunk would be shorter than 50 words, merge it with the most closely related adjacent chunk. "
        "Prioritize topic coherence over meeting the size target, do not merge unrelated topics just to reach 100 words.\n"
        "3. If a code example directly illustrates the preceding explanation, keep them in the SAME chunk.\n"
        "4. If a code example is standalone or paired with minimal prose, it may be its own chunk.\n"
        "5. If this chunk continues directly from the previous one, populate the context field "
        "with a 1-sentence summary of what the previous chunk covered. Do not describe what comes next.\n\n"
        "## Text to process\n"
        f"{text}"
    )
    
    try:
        result = structured_llm.invoke(prompt)
        documents = []
        for section in result.sections:
            # User Strategy: Embed Summary, Retrieve Original via Metadata
            doc = Document(
                page_content=section.summary,  # This is what gets embedded
                metadata={
                    "original_content": section.content, # This is the full context
                    "context": section.context,
                    "category": "spring_boot_reference"
                }
            )
            documents.append(doc)
        return documents
    except Exception as e:
        print(f"Error during LLM splitting: {e}")
        # Fallback to simple splitting if LLM fails
        split_content = split_text(text)
        documents = []
        for content in split_content:
            doc = Document(
                page_content=content.page_content,
                metadata={
                    "original_content": content.page_content,
                    "context": "",
                    "category": "spring_boot_reference"
                }
            )
            documents.append(doc)
        return documents

async def split_text_with_llm_async(text, model_name="gpt-5-mini"):
    """
    Splits the full text into logical sections using an LLM asynchronously.
    Returns a list of Document objects.
    """
    if not text:
        return []
        
    llm = ChatOpenAI(model=model_name, temperature=0)
    structured_llm = llm.with_structured_output(PageSections)
    
    prompt = (
        "You are a technical documentation processor specializing in RAG pipeline preparation.\n\n"
        "## Goal\n"
        "Split the documentation into chunks where each chunk can independently answer "
        "a specific user question without requiring context from other chunks.\n\n"
        "## Chunking Rules\n"
        "1. Each chunk should represent only ONE distinct concept, behavior, or use case.\n"
        "2. Aim for 100 to 300 words per chunk. "
        "If a chunk would be shorter than 50 words, merge it with the most closely related adjacent chunk. "
        "Prioritize topic coherence over meeting the size target, do not merge unrelated topics just to reach 100 words.\n"
        "3. If a code example directly illustrates the preceding explanation, keep them in the SAME chunk.\n"
        "4. If a code example is standalone or paired with minimal prose, it may be its own chunk.\n"
        "5. If this chunk continues directly from the previous one, populate the context field "
        "with a 1-sentence summary of what the previous chunk covered. Do not describe what comes next.\n\n"
        "## Text to process\n"
        f"{text}"
    )
    
    try:
        result = await structured_llm.ainvoke(prompt)
        documents = []
        for section in result.sections:
            doc = Document(
                page_content=section.summary,  # This is what gets embedded
                metadata={
                    "original_content": section.content, # This is the full context
                    "context": section.context,
                    "category": "spring_boot_reference"
                }
            )
            documents.append(doc)
        return documents
    except Exception as e:
        print(f"Error during Async LLM splitting: {e}")
        # Fallback to simple splitting if LLM fails
        split_content = split_text(text)
        documents = []
        for content in split_content:
            doc = Document(
                page_content=content.page_content,
                metadata={
                    "original_content": content.page_content,
                    "context": "",
                    "category": "spring_boot_reference"
                }
            )
            documents.append(doc)
        return documents
    """
    Uses LLM to generate a concise summary or keywords for the chunk.
    This metadata can be stored with the chunk for better retrieval.
    """
    if not llm:
        llm = ChatOpenAI(model="gpt-5-mini", temperature=0)

    prompt = PromptTemplate.from_template(
        "Summarize the key technical concepts in the following text in 1 sentence:\n\n{text}"
    )
    chain = prompt | llm
    try:
        summary = chain.invoke({"text": chunk_text})
        return summary.content
    except Exception as e:
        print(f"Error enhancing chunk: {e}")
        return ""

def process_documents(documents, use_llm=False):
    """
    Iterates through documents and optionally adds LLM-generated metadata.
    """
    if use_llm:
        print(f"Enhancing {len(documents)} chunks with LLM...")
        llm = ChatOpenAI(model="gpt-5-mini", temperature=0)
        for i, doc in enumerate(documents):
            print(f"Processing chunk {i+1}/{len(documents)}...")
            summary = enhance_chunk_with_llm(doc.page_content, llm)
            doc.metadata["summary"] = summary
    return documents
